import { diagnose, PLAIN, type Diagnosis } from './diagnose.js';
export { renderHtml } from './report-html.js';
import type { ScenarioResult } from './core.js';

export type Row = Omit<ScenarioResult, 'screenshot'> & { screenshot?: string; project: string; retry: number; file: string };
export interface RenderInput { rows: Row[]; generatedAt: string; rerun: (file: string) => string; image: (png: string) => string | undefined }

/** One thing to fix, shared by every scenario that failed for the same reason. */
export interface Issue { d: Diagnosis; rows: Row[] }

export const plural = (n: number, one: string, many = one + 's') => `${n} ${n === 1 ? one : many}`;

/** Failures first, then warnings. Scenarios with the same diagnosis become one issue. */
export function issues(rows: Row[]): Issue[] {
  const byTitle = new Map<string, Issue>();
  const evidence = new Map<string, number>();
  for (const r of rows) {
    const d = diagnose(r);
    if (!d) continue;
    const key = `${r.file}\u0000${d.title}`;
    const hit = byTitle.get(key);
    if (!hit) { byTitle.set(key, { d, rows: [r] }); evidence.set(key, r.failedRequests.length); continue; }
    hit.rows.push(r);
    // keep the diagnosis built from the richest evidence (its snippet lists the most missing files)
    if (r.failedRequests.length > evidence.get(key)!) { hit.d = d; evidence.set(key, r.failedRequests.length); }
  }
  const rank = { fail: 0, warn: 1, info: 2 };
  return [...byTitle.values()].sort((a, b) => rank[a.d.severity] - rank[b.d.severity]);
}

/** Plain instructions for a coding agent: evidence, likely cause, steps, and how to verify. */
export function renderMarkdown({ rows, generatedAt, rerun }: RenderInput): string {
  const list = issues(rows);
  const fails = rows.filter((r) => r.status === 'failed').length;
  const files = [...new Set(rows.map((r) => r.file))];
  const out: string[] = [
    '# Offline fix plan',
    '',
    `Generated by OfflineCheck on ${generatedAt} for ${[...new Set(rows.map((r) => r.url))].join(', ')}.`,
    '',
    fails
      ? `${fails} of ${rows.length} offline checks failed, from ${plural(list.filter((i) => i.d.severity === 'fail').length, 'cause')}. Work through the issues in order: an earlier fix often clears later failures too.`
      : list.length ? `No check failed. ${plural(list.length, 'item')} below still need attention.` : `All ${rows.length} offline checks passed. Nothing to fix.`,
    '',
    '## Rules',
    '',
    '- Fix the app, not the test. Do not weaken, skip or delete OfflineCheck scenarios or their assertions.',
    '- Change the spec\'s `ready` function only to wait for a real readiness signal, such as service worker control. Never add fixed sleeps.',
    '- Each cause below is inferred from the step that broke. Confirm it in the code before changing anything.',
    '- Re-run the check after each fix. The task is done when every scenario reports `passed`, or `skipped` only for a documented test-tool limitation.',
    '',
    '## Verify',
    '',
    ...files.flatMap((f) => ['```bash', rerun(f), '```']),
    '',
  ];
  list.forEach(({ d, rows: rs }, n) => {
    out.push(
      `## ${n + 1}. ${d.title}`,
      '',
      `Severity: ${d.severity === 'fail' ? 'failure' : d.severity === 'warn' ? 'warning' : 'note, no app change needed'}. Scenarios: ${rs.map((r) => `\`${r.scenario}\` on ${r.project}${r.device ? ` (${r.device})` : ''} (${r.status}${r.status === 'failed' ? ` at \`${r.phase}\`` : ''})`).join(', ')}. Spec: \`${rs[0].file}\`.`,
      '',
      `**What happened.** ${d.happened}`,
      '',
      `**Likely cause.** ${d.cause}`,
      '',
      '**Steps:**',
      '',
      ...d.steps.map((s) => `- [ ] ${s}`),
      '',
      ...(d.snippet ? ['Starting point (adapt paths and names to the app):', '', '```' + d.snippet.lang, d.snippet.code, '```', ''] : []),
      '**Evidence:**',
      '',
    );
    for (const r of rs) {
      out.push(`- \`${r.scenario}\`: ${r.exercised.length ? 'completed ' + r.exercised.join(', ') : 'completed nothing'}.`);
      if (r.error) out.push(`  - Error: \`${r.error.replace(/`/g, "'")}\``);
      if (r.swRegistered !== undefined) out.push(`  - Page had registered a service worker: ${r.swRegistered ? 'yes' : 'no'}`);
      if (r.serviceWorker) out.push(`  - Service worker controlled the offline load: ${r.serviceWorker === 'controlled' ? 'yes' : 'no'}`);
      for (const [label, xs] of [['Failed request', r.failedRequests], ['Console error', r.consoleErrors], ['Page error', r.pageErrors]] as const)
        for (const x of xs) out.push(`  - ${label}: \`${x.replace(/`/g, "'")}\``);
    }
    out.push('');
  });
  const works = rows.filter((r) => r.status === 'passed' && !diagnose(r));
  if (works.length) out.push('## Already passing', '', ...works.map((r) => `- \`${r.scenario}\`: ${PLAIN[r.scenario]}`), '');
  return out.join('\n');
}
